#!/bin/bash
if [ ${#LIST[@]} = 0 ]; then
	export LIST=()
fi

list.add() {
	if [ $# = 0 ]; then
		return
	fi
	for i in $@;
	do
		LIST+=($i)
	done
}

list.show() {
	if [ ${#LIST[@]} = 0 ]; then
		return
	fi
	for i in ${LIST[@]};
	do
		echo $i
	done
}

list.clear() {
	export LIST=()
}
